<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rover_bringup</name>
  <version>0.1.0</version>
  <description>Top-level and simulation bringup: aggregated launch files and parameters for the full pipeline.</description>
  <maintainer email="zeynep@sabanciuniv.edu">Zeynep Altundal</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rover_description</depend>
  <depend>rover_control</depend>
  <depend>rover_kinematics</depend>
  <depend>rover_navigation</depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
